@host = laughing-telegram-qjpxpgqwxx6f65rg-3000.app.github.dev
@session = session=2facd737824917b06813da49cfe00a9e4af334bbf920e9bc6072956d49804a91; Path=/; Expires=Sun, 12 Oct 2025 01:39:44 GMT; HttpOnly; SameSite=lax
@email = silvino@gmail.com
@password = xemwus-pemguk-Zesdi9

###
GET /api/ping HTTP/1.1
Host: {{host}}
Accept: application/json

### Sign Up
POST /api/sign-up HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "name": "Silvino"
}

### Sign In
POST /api/sign-in HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Me
GET /api/me HTTP/1.1
Host: {{host}}
Cookie: {{session}}

### Sign Out
POST /api/sign-out HTTP/1.1
Host: {{host}}
Cookie: {{session}}