# @host = laughing-telegram-qjpxpgqwxx6f65rg-3000.app.github.dev
@host = localhost:3000
@session = d6647ebd1cd2c4c0e55609242f4b0ea7b31452b1b2ad90d81a72c483d93cdfe2
@name = Silvino
@email = {{name}}@devcore.dev
@password = g5XJOWbcFKE=

###
GET /api/ping HTTP/1.1
Host: {{host}}
Accept: application/json

### Sign Up
POST /api/sign-up HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "name": "{{name}}"
}

### Sign In
POST /api/sign-in HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Me
GET /api/me HTTP/1.1
Host: {{host}}
Accept: application/json

### Sign Out
POST /api/sign-out HTTP/1.1
Host: {{host}}
